version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrdersApiUrl=http://ordersapi
    ports:
      - "5998:80"


  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FacesApiUrl=http://api
      - OrdersContextConnection=Server=mssql;Database=FACEORDER; user id=sa;password=Insecure!12345;
    ports:
      - "6002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
